# Generated by Django 6.0.3 on 2026-04-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="filmworkgenre",
            name="film_work_genre",
        ),
        migrations.RemoveIndex(
            model_name="personrole",
            name="film_work_person_role",
        ),
        migrations.AddIndex(
            model_name="filmworkgenre",
            index=models.UniqueConstraint(fields=("filmwork_id", "genre_id"), name="film_work_genre"),
        ),
        migrations.AddIndex(
            model_name="personrole",
            index=models.UniqueConstraint(fields=("filmwork_id", "person_id", "role"), name="film_work_person_role"),
        ),
    ]
